### ISSUE TITLE
Coud not connect

### ISSUE THREAD

**Issue by phaalonso** [BubbatheVTOG/coc-discord-neovim#4] opened 2020-06-30 14:12 UTC
Hi, I am having some problems with the rpc. 

```
## versions

vim version: NVIM v0.4.3
node version: v12.18.1
coc.nvim version: 0.0.78
coc.nvim directory: /home/pedro/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Output channel: discord-neovim

[Info  - 11:10:51 AM] - Creaing coc-discord-neovim client with client ID: 721172077033553950
[Erro  - 11:10:51 AM] - Error: Could not connect
```

**Comment by BubbatheVTOG** [comment] 2020-07-08 21:38
Hello phaalanso,

Sorry it took so long for me to notice this. Github didn't notify me of this issue.

This is the output returned from the ipc client attempting to connect to your desktop Discord client ([preformed here](https://github.com/BubbatheVTOG/coc-discord-neovim/blob/f081407e18b3458c1529eba7a8ae7ec82647fe8c/src/coc-discord-client.ts#L35)). This most likely means that you did have Discord started when you opened nvim, which triggered the ipc client to attempt to connect to your desktop's Discord client, which it was not able to do. This is an exit due to the failure to meet a runtime dependency - a running Discord desktop client - and is simply a log of what the ipc client is returning. This is an intended behavior, though if you think that this message should be different or if you think we should change this behavior I'm open to PR's. 

I'm closing this issue for now since it is an intended behavior.

**Closed by BubbatheVTOG** 2020-07-08 21:38 UTC
